name: Deploy React Client

on:
  push:
    branches: [ main ]
    paths:
      - 'client/**'  # Only trigger when client files change

jobs:
  deploy-client:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          
      - name: Install & Build
        run: |
          npm install
          npm run build
          
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_HILL_07E8AD610 }}
          app_location: "client"
          output_location: "build"  # For CRA. Use "dist" for Vite
          skip_app_build: true
