name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [main]
    paths: 
      - 'client/**'  # Only rebuild when client files change

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
      deployments: write

    steps:
      # 1. Checkout with full history
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # 2. Setup Node.js 20.x
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: 'client/package-lock.json'

      # 3. Optimized build process
      - name: Build Client
        working-directory: client
        env:
          NODE_OPTIONS: '--experimental-global-webcrypto'
        run: |
          # Clean install
          npm ci --prefer-offline
          
          # Build with Vite
          npm run build
          
          # Azure-required configuration
          echo '{
            "routes": [
              {
                "route": "/*",
                "serve": "/index.html", 
                "statusCode": 200
              }
            ],
            "navigationFallback": {
              "rewrite": "/index.html"
            },
            "mimeTypes": {
              ".wasm": "application/wasm"
            }
          }' > dist/routes.json
          
          # Remove unnecessary files
          find dist/ -type f \( -name "*.map" -o -name "*.txt" \) -delete

      # 4. Verify output
      - name: Audit Build
        working-directory: client
        run: |
          echo "=== Build Artifacts ==="
          ls -lh dist/
          echo -e "\n=== Total Files ===" 
          find dist/ -type f | wc -l

      # 5. Deploy with your EXACT secret name
      - name: Deploy to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_MUD_02BBDB203 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "client"  # Source code
          app_artifact_location: "dist"  # Built files
          skip_app_build: true  # Critical for pre-built files
          verbose: true
